- backend/src/game/dice.py
- backend/test/game/test_dice.py
Ran some tests using pytest showing that both rolling and multiple
rolls work correctly.
> Adding dice.py!

- frontend/src/containers/Login.js
Added play as guest option in Login container that redirects user to Lobby
> Added play as guest option

- build_and_run_project.py
- sonar-project.properties
This is tested for Windows 10, but it should also be able to work
on Linux/Mac.
The only thing I'm not 100% on is the fact that I have global
variables in the file itself. The constants file is nested in
the game folder, so this seemed like it should be separate from
that. Maybe a new constants file at the main folder level for
this? Seemed weird to have for only one thing, that's why I
didn't just do it.
> Created a script to quickly build the required react files and run

- backend/game/newcards/conftest.py
- backend/game/newcards/discard_cards/victory_point_manipulation_cards/corner_store.py
- backend/game/newcards/discard_cards/victory_point_manipulation_cards/evacuation_orders.py
- backend/game/newcards/discard_cards/victory_point_manipulation_cards/test_corner_store.py
- backend/game/newcards/discard_cards/victory_point_manipulation_cards/test_evacuation_orders.py
A pull request for adding additional cards to the game (re-made after the python reorganization)
> Adding additional cards

- backend/game/constants.py
- backend/game/player.py
- backend/game/turn.py
- backend/test/test_player.py
- backend/test/test_turn.py
Adds energy for player
Adds ability to get attacking players
Adds attacking players
Determines if a player is able to be attacked
> Game turn -  Attack

- README.md
added cliff notes outlining how to setup, run and test Python and React
> Python and React steps

- README.md
added steps to call pip install -r requirements.txt an extra time after upgrading pip
> quick start tweaks

- backend/game/dice/dice_resolver.py
- backend/game/dice/test_dice_resolver.py
Small change to make dice_resolver automatically update player energy
> attached player to energy resolution in dice_resolver

- backend/game/cards/master_card_list.py
I found some cards in master branch where the class was created but they were not added to the master cards list so they would not be in the deck. I added them to the list and did a little reorganizing by adding discard_cards array to keep this organized as it expands. 
No logic changes
> Added cards found in Cards directories to the master card list

- frontend/package-lock.json
- frontend/package.json
ran npm audit fix to clear up two vulnerability warnings
> applied audit fixes

- backend/game/deck/deck_handler.py
- backend/game/deck/deck_handler_test.py
- backend/game/player/player.py
- backend/game/values/constants.py
Simple edits to make purchasing cards actually cost energy
NOTE: This implements the List change that Gerardo suggested in #57 review notes which could lead to some conflicting work.
> Made cards cost energy, added player list of cards

- backend/game/cards/keep_card.py
- backend/game/cards/keep_cards/nova_breath.py
- backend/game/player/player.py
- backend/game/player/test_player.py
- backend/game/turn_actions/attack.py
- backend/game/turn_actions/test_attack.py
Copied the Keep card abstract class I think from @kaubster PR #73.
Since this card only modifies the targets of attack rolls no trigger logic is necessary, just check if attacker owns this card
> NovaBreath Keep card 

- backend/game/engine/board.py
- backend/lobby/consumers.py
Sample of attaching deckhandler to gameconsumer.
NOTE: this PR doesn't merge to Master, but in to Lakshmi's branch, I just did this to separate so it can be applied as needed. 
Keith I just added you since you were on the call in case you're interested
> demonstrate attach deckhandler to frontend GameConsumer

- backend/game/dice/dice_resolver.py
I noticed a small mistake in dice resolver. We should be moving to tokyo if empty on rolling at least one die, not > 1 die.
> Quick bugfix

- .gitignore
- .vscode/settings.json
> Updating settings.json for relative pathing

- backend/game/cards/discard_card.py
- backend/game/cards/discard_cards/energy_manipulation_cards/energize.py
- backend/game/cards/discard_cards/energy_manipulation_cards/test_energize.py
- backend/game/cards/discard_cards/health_manipulation_cards/fire_blast.py
- backend/game/cards/discard_cards/health_manipulation_cards/heal.py
- backend/game/cards/discard_cards/health_manipulation_cards/high_altitude_bombing.py
- backend/game/cards/discard_cards/health_manipulation_cards/test_fire_blast.py
- backend/game/cards/discard_cards/health_manipulation_cards/test_heal.py
- backend/game/cards/discard_cards/health_manipulation_cards/test_high_altitude_bombing.py
- backend/game/cards/discard_cards/multi_manipulation_cards/gas_refinery.py
- backend/game/cards/discard_cards/multi_manipulation_cards/jet_fighters.py
- backend/game/cards/discard_cards/multi_manipulation_cards/national_guard.py
- backend/game/cards/discard_cards/multi_manipulation_cards/nuclear_power_plant.py
- backend/game/cards/discard_cards/multi_manipulation_cards/tanks.py
- backend/game/cards/discard_cards/multi_manipulation_cards/test_gas_refinery.py
- backend/game/cards/discard_cards/multi_manipulation_cards/test_jet_fighters.py
- backend/game/cards/discard_cards/multi_manipulation_cards/test_national_guard.py
- backend/game/cards/discard_cards/multi_manipulation_cards/test_nuclear_power_plant.py
- backend/game/cards/discard_cards/multi_manipulation_cards/test_tanks.py
- backend/game/cards/discard_cards/multi_manipulation_cards/test_vast_storm.py
- backend/game/cards/discard_cards/multi_manipulation_cards/vast_storm.py
- backend/game/cards/discard_cards/victory_point_manipulation_cards/apartment_building.py
- backend/game/cards/discard_cards/victory_point_manipulation_cards/commuter_train.py
- backend/game/cards/discard_cards/victory_point_manipulation_cards/corner_store.py
- backend/game/cards/discard_cards/victory_point_manipulation_cards/evacuation_orders.py
- backend/game/cards/discard_cards/victory_point_manipulation_cards/skyscraper.py
- backend/game/cards/keep_card.py
added card types to discard and keep subclass
> changed discard cards to call super instead of Card.__init__

- backend/game/cards/keep_cards/energy_manipulation_cards/friend_of_children.py
- backend/game/cards/keep_cards/energy_manipulation_cards/test_friend_of_children.py
- backend/game/player/player.py
Pass through special effect
Added test  #106
> Adding friend of children

- backend/game/cards/card.py
- backend/game/cards/test_card.py
- backend/game/values/constants.py
These methods will be helpful for @Lakshmii3 to send cards to the frontend for the UI
> added to_dict and to_json methods for cards

- frontend/src/components/Cards/CardStore.js
I don't think we need this button, can you please confirm? If so, feel free to merge it
> remove card store button

- .vscode/settings.json
- backend/game/cards/keep_cards/victory_point_manipulation_cards/dedicated_news_team.py
- backend/game/cards/keep_cards/victory_point_manipulation_cards/test_dedicated_news_team.py
- backend/game/cards/master_card_list.py
- backend/game/deck/deck_handler.py
> Adding dedicated news team card

- backend/game/cards/keep_cards/victory_point_manipulation_cards/gourmet.py
- backend/game/cards/keep_cards/victory_point_manipulation_cards/test_gourmet.py
- backend/game/cards/master_card_list.py
- backend/game/dice/dice_resolver.py
Another day, another keep card resolves #109
> Gourmet card

- backend/game/cards/keep_cards/victory_point_manipulation_cards/omnivore.py
- backend/game/cards/keep_cards/victory_point_manipulation_cards/test_omnivore.py
- backend/game/cards/master_card_list.py
- backend/game/dice/dice_resolver.py
> Omnivore card

- backend/lobby/consumers.py
> lock buy cards to current player

- backend/game/cards/discard_cards/energy_manipulation_cards/energize.py
- backend/game/cards/discard_cards/health_manipulation_cards/fire_blast.py
- backend/game/cards/discard_cards/health_manipulation_cards/heal.py
- backend/game/cards/discard_cards/health_manipulation_cards/high_altitude_bombing.py
- backend/game/cards/discard_cards/multi_manipulation_cards/gas_refinery.py
- backend/game/cards/discard_cards/multi_manipulation_cards/jet_fighters.py
- backend/game/cards/discard_cards/multi_manipulation_cards/national_guard.py
- backend/game/cards/discard_cards/multi_manipulation_cards/nuclear_power_plant.py
- backend/game/cards/discard_cards/multi_manipulation_cards/tanks.py
- backend/game/cards/discard_cards/multi_manipulation_cards/vast_storm.py
- backend/game/cards/discard_cards/victory_point_manipulation_cards/commuter_train.py
- backend/game/cards/discard_cards/victory_point_manipulation_cards/corner_store.py
- backend/game/cards/discard_cards/victory_point_manipulation_cards/drop_from_high_altitude.py
- backend/game/cards/discard_cards/victory_point_manipulation_cards/test_drop_from_high_altitude.py
- backend/game/cards/keep_card.py
- backend/game/cards/keep_cards/attack_manipulation_cards/nova_breath.py
- backend/game/cards/keep_cards/health_manipulation_cards/even_bigger.py
- backend/game/cards/keep_cards/health_manipulation_cards/it_has_a_child.py
- backend/game/cards/keep_cards/health_manipulation_cards/test_it_has_a_child.py
- backend/game/cards/master_card_list.py
- backend/game/cards/test_card.py
- backend/game/player/player.py
- backend/game/turn_actions/attack.py
- backend/game/turn_actions/player_movement.py
- backend/game/turn_actions/test_attack.py
- backend/game/turn_actions/test_player_movement.py
Added keep card does proper super
Added NovaCard to own folder type (fixed its references)
Added back drop from high altitude
Fixed energize card name
> Various card fixes

- backend/game/cards/keep_cards/health_manipulation_cards/regeneration.py
- backend/game/cards/keep_cards/health_manipulation_cards/test_regeneration.py
- backend/game/cards/master_card_list.py
- backend/game/player/player.py
> Adding card regeneration

- backend/game/engine/board.py
- backend/lobby/consumers.py
Fixes SolarPowered/EnergyHoarder calls #208
> Adds end-turn cards to gameplay by including them in consumers.py

- backend/game/engine/board.py
- backend/lobby/consumers.py
- frontend/src/containers/Gameboard.js
recovered missing render() portion from Gameboard.js
Commented out problematic card code from board.py
see issue #234 for details on board.py
> Recover failing build

- frontend/src/components/Alerts/ChooseYielderAlert.js
this file should have been included in #238
> Adding missing yielder alert class

- backend/game/cards/keep_cards/victory_point_manipulation_cards/eater_of_the_dead.py
- backend/game/cards/keep_cards/victory_point_manipulation_cards/test_eater_of_the_dead.py
- backend/game/cards/master_card_list.py
- backend/game/engine/player_queue.py
- backend/game/player/player.py
- backend/game/player/test_player.py
- backend/lobby/consumers.py
See demonstration in Cards channel on slack
> Eater of the Dead death trigger

- README.md
- backend/README.md
- frontend/README.md
Updated readme.md within root, frontend and backend
> updating readme.md

- README.md
- backend/lobby/consumers.py
- frontend/src/components/PlayerValues/PlayerHandDisplay.js
Readme.md tweaks
fixed warning that turned out to be error
> readme update, fixed warning that turned out to be error

- backend/lobby/consumers.py
- frontend/package-lock.json
- frontend/src/components/Dice/DiceRoller.js
- frontend/src/components/Dice/__snapshots__/DiceRoller.test.js.snap
Adds a button to start the game under the roll buttons. Button goes away after starting game. 
Game automatically starts after 4 players join
Doesn't handle page refresh well....
> Start game on button press

- backend/game/cards/keep_cards/attack_manipulation_cards/spiked_tail.py
- backend/game/cards/master_card_list.py
- backend/game/dice/dice_resolver.py
> spiked tail add
